=== nanreh/calendar-hack/public/schema/plan-schema.json
{
    "description": "Plan schema",
    "$id": "https://defy.org/plan",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "pattern": "^[a-z0-9]+(?:_[a-z0-9]+)*$"
        },
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "type": {
            "enum": [
                "Base",
                "Multiple Distances",
                "Marathon",
                "Half Marathon",
                "5K",
                "10K",
                "15K/10M",
                "50K",
                "100K",
                "100M"
            ]
        },
        "units": {
            "enum": [
                "mi",
                "km"
            ]
        },
        "source": {
            "type": "string"
        },
        "schedule": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/week"
            },
            "minItems": 1
        }
    },
    "required": [
        "id",
        "name",
        "description",
        "units",
        "source",
        "type",
        "schedule"
    ],
    "definitions": {
        "week": {
            "type": "object",
            "properties": {
                "description": {"type": "string"},
                "distance": {"type": "number"},
                "workouts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/workout"
                    },
                    "minItems": 7,
                    "maxItems": 7
                }
            },
            "required": [
                "workouts"
            ]
        },
        "workout": {
            "type": "object",
            "properties": {
                "title": {"type": "string"},
                "description": {"type": "string"},
                "distance": {
                    "anyOf": [
                      { "type": "number" },
                      {
                        "type": "array",
                        "items": { "type": "number" },
                        "minItems": 2,
                        "maxItems": 2
                      }
                    ]
                  },
                "tags": {
                    "type": "array",
                    "items": {
                        "enum": [
                            "Rest",
                            "Easy Run",
                            "Run",
                            "Long Run",
                            "Cross Train",
                            "Race",
                            "Speedwork",
                            "Hills"
                        ]
                    },
                    "minItems": 1,
                    "uniqueItems": true
                }
            },
            "required": [
                "title"
            ]
        }
    }
}

=== nanreh/calendar-hack/public/plans/json/higdon_nov_half2.json
{
   "id": "higdon_nov_half2",
   "name": "Hal Higdon: Half Marathon Novice 2",
   "description": "Hal Higdon: Half Marathon Novice 2 fills the gap between the former Novice (now Novice 1) half marathon program and the Intermediate programs. Pace runs in the plan are  at the pace you plan to run in the race you\u2019re training for.",
   "units": "mi",
   "source": "https://www.halhigdon.com/training-programs/half-marathon-training/novice-2-half-marathon/",
   "type": "Half Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "{4:6.4} run",
               "distance": 4.0
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{3:4.8} pace",
               "distance": 3.0
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "{5:8.1} run",
               "distance": 5.0
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{4:6.4} run",
               "distance": 4.0
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "{6:9.7} run",
               "distance": 6.0
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{4:6.4} pace",
               "distance": 4.0
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "{7:11.3} run",
               "distance": 7.0
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{4:6.4} run",
               "distance": 4.0
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "{8:12.9} run",
               "distance": 8.0
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{4:6.4} pace",
               "distance": 4.0
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "5K race",
               "distance": 3.1
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{5:8.1} run",
               "distance": 5.0
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "{9:14.5} run",
               "distance": 9.0
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{5:8.1} pace",
               "distance": 5.0
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "{10:16.1} run",
               "distance": 10.0
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{5:8.1} run",
               "distance": 5.0
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "10K race",
               "distance": 6.2
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{5:8.1} pace",
               "distance": 5.0
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "{11:17.7} run",
               "distance": 11.0
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{5:8.1} run",
               "distance": 5.0
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "{12:19.3} run",
               "distance": 12.0
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{2:3.2} run",
               "distance": 2.0
            },
            {
               "title": "{2:3.2} run",
               "distance": 2.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Half Marathon ({13.1:21.1})",
               "distance": 13.1
            }
         ]
      }
   ]
}

=== nanreh/calendar-hack/public/plans/json/pfitz_08_multi.json
{
   "id": "pfitz_08_multi",
   "name": "Pfitzinger/Douglas: Multiple Marathoning, 8-week schedule",
   "description": "\"Multiple Marathoning, 8-week schedule\" from \"Advanced Marathoning\" (third edition) by Pete Pfitzinger and Scott Douglas",
   "units": "mi",
   "source": "https://www.amazon.com/gp/product/149256866X/",
   "type": "Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "Recovery {7:11}",
               "distance": 7.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {7:11} with 8 x 100 m strides",
               "distance": 7.0
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "Gen-aerobic {10:16}",
               "distance": 10.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6.0
            },
            {
               "title": "Gen-aerobic {9:14}",
               "distance": 9.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {9:14} with 8 x 100 m strides",
               "distance": 9.0
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "Med-long run {13:21}",
               "distance": 13.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {8:13} with 6 x 10 sec hill sprints + 8 x 100 m strides",
               "distance": 8.0
            },
            {
               "title": "Med-long run {12:19}",
               "distance": 12.0
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4.0
            },
            {
               "title": "LT {9:14} with {5:8} at LT pace",
               "distance": 9.0
            },
            {
               "title": "Recovery + speed {5:8} with 6 x 100 m strides",
               "distance": 5.0
            },
            {
               "title": "Long run {17:27}",
               "distance": 17.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6.0
            },
            {
               "title": "VO\u2082max {10:16} with 5 x 1,000 m at 5K race pace; jog 50-90% interval time",
               "distance": 10.0
            },
            {
               "title": "Med-long run {15:24}",
               "distance": 15.0
            },
            {
               "title": "Gen-aerobic {9:14}",
               "distance": 9.0
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6.0
            },
            {
               "title": "Long run {20:32}",
               "distance": 20.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "VO\u2082max {9:14} with 6 x 600 m at 5K race pace; jog 50-90% interval time",
               "distance": 9.0
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11.0
            },
            {
               "title": "Recovery + speed {6:10} with 6 x 100 m strides",
               "distance": 6.0
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "8K-10K tune-up race (total 9-11 miles [14-18 km])",
               "distance": 9.0
            },
            {
               "title": "Long run {17:27}",
               "distance": 17.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {8:13} with 8 x 100 m strides",
               "distance": 8.0
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "VO\u2082max {9:14} with 4 x 1,200 m at 5K race pace; jog 50-90% interval time",
               "distance": 9.0
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "Recovery + speed {6:10} with 8 x 100 m strides",
               "distance": 6.0
            },
            {
               "title": "Med-long run {13:21}",
               "distance": 13.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6.0
            },
            {
               "title": "Dress rehearsal {7:11} with {2:3} at marathon pace",
               "distance": 7.0
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6.0
            },
            {
               "title": "Recovery + speed {5:8} with 6 x 100 m strides",
               "distance": 5.0
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4.0
            },
            {
               "title": "Second Marathon",
               "distance": 26.2
            }
         ]
      }
   ]
}

=== nanreh/calendar-hack/public/plans/json/higdon_half3.json
{
   "id": "higdon_half3",
   "name": "Hal Higdon: Half Marathon 3",
   "description": "Hal Higdon: Half Marathon 3 (HM3): \"Welcome to Half Marathon 3, or HM3. This is a new program created for Hal Higdon's Half Marathon Training. It was designed to match the popular Marathon 3 program that features 3 days of running a week and 2 days of cross-training. It recognizes the fact that not all runners can handle 4, 5, 6 and especially not 7 days of running a week. We are all different and achieve success by various means. HM3 lasts 12 weeks aimed at the half marathon of your choice. In signing up for HM3, be sure to set the correct end date so all of the workouts fall into place for your goal race. Monday in HM3 is always a day of rest to recover from the hard training on the weekend. Tuesdays and Thursdays are easy running days, conversational pace mostly. In between on Wednesdays, you cross train, the most popular form of cross-training being aerobic: cycling, swimming or even walking. Friday is another rest day with long runs on Saturdays and cross-training on Sundays, although you can flipflop those workouts for convenience.\" (more details at the link below)",
   "units": "mi",
   "source": "https://www.halhigdon.com/training-programs/half-marathon-training/half-marathon-3",
   "type": "Half Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{4:6.4} run",
               "distance": 4.0
            },
            {
               "title": "30 min cross"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "{6:9.7} run",
               "distance": 6.0
            },
            {
               "title": "30 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{4:6.4} run",
               "distance": 4.0
            },
            {
               "title": "35 min cross"
            },
            {
               "title": "30 min tempo"
            },
            {
               "title": "Rest"
            },
            {
               "title": "{6:9.7} run",
               "distance": 6.0
            },
            {
               "title": "35 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{5:8.1} run",
               "distance": 5.0
            },
            {
               "title": "40 min cross"
            },
            {
               "title": "{3:4.8} pace",
               "distance": 3.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "{7:11.3} run",
               "distance": 7.0
            },
            {
               "title": "40 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{5:8.1} run",
               "distance": 5.0
            },
            {
               "title": "45 min cross"
            },
            {
               "title": "{4:6.4} run",
               "distance": 4.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "{7:11.3} run",
               "distance": 7.0
            },
            {
               "title": "45 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{4:6.4} run",
               "distance": 4.0
            },
            {
               "title": "50 min cross"
            },
            {
               "title": "40 min tempo"
            },
            {
               "title": "Rest"
            },
            {
               "title": "{8:12.9} run",
               "distance": 8.0
            },
            {
               "title": "50 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{4:6.4} run",
               "distance": 4.0
            },
            {
               "title": "30 min cross"
            },
            {
               "title": "{3:4.8} pace",
               "distance": 3.0
            },
            {
               "title": "Rest or easy run"
            },
            {
               "title": "Rest"
            },
            {
               "title": "5-K Race"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{6:9.7} run",
               "distance": 6.0
            },
            {
               "title": "50 min cross"
            },
            {
               "title": "{5:8.1} run",
               "distance": 5.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "{9:14.5} run",
               "distance": 9.0
            },
            {
               "title": "50 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{6:9.7} run",
               "distance": 6.0
            },
            {
               "title": "50 min cross"
            },
            {
               "title": "50 min tempo"
            },
            {
               "title": "Rest"
            },
            {
               "title": "{9:14.5} run",
               "distance": 9.0
            },
            {
               "title": "50 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{4:6.4} run",
               "distance": 4.0
            },
            {
               "title": "30 min cross"
            },
            {
               "title": "{3:4.8} pace",
               "distance": 3.0
            },
            {
               "title": "Rest or easy run"
            },
            {
               "title": "Rest"
            },
            {
               "title": "10-K Race"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{6:9.7} run",
               "distance": 6.0
            },
            {
               "title": "60 min cross"
            },
            {
               "title": "{6:9.7} run",
               "distance": 6.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "{10:16.1} run",
               "distance": 10.0
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{6:9.7} run",
               "distance": 6.0
            },
            {
               "title": "60 min cross"
            },
            {
               "title": "60 min tempo"
            },
            {
               "title": "Rest"
            },
            {
               "title": "{10:16.1} run",
               "distance": 10.0
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{4:6.4} run",
               "distance": 4.0
            },
            {
               "title": "30 min cross"
            },
            {
               "title": "{3:4.8} pace",
               "distance": 3.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Half Marathon ({13.1:21.1})",
               "distance": 13.1
            }
         ]
      }
   ]
}
