=== nanreh/calendar-hack/public/schema/plan-schema.json
{
    "description": "Plan schema",
    "$id": "https://defy.org/plan",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "pattern": "^[a-z0-9]+(?:_[a-z0-9]+)*$"
        },
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "type": {
            "enum": [
                "Base",
                "Multiple Distances",
                "Marathon",
                "Half Marathon",
                "5K",
                "10K",
                "15K/10M",
                "50K",
                "100K",
                "100M"
            ]
        },
        "units": {
            "enum": [
                "mi",
                "km"
            ]
        },
        "source": {
            "type": "string"
        },
        "schedule": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/week"
            },
            "minItems": 1
        }
    },
    "required": [
        "id",
        "name",
        "description",
        "units",
        "source",
        "type",
        "schedule"
    ],
    "definitions": {
        "week": {
            "type": "object",
            "properties": {
                "description": {"type": "string"},
                "distance": {"type": "number"},
                "workouts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/workout"
                    },
                    "minItems": 7,
                    "maxItems": 7
                }
            },
            "required": [
                "workouts"
            ]
        },
        "workout": {
            "type": "object",
            "properties": {
                "title": {"type": "string"},
                "description": {"type": "string"},
                "distance": {
                    "anyOf": [
                      { "type": "number" },
                      {
                        "type": "array",
                        "items": { "type": "number" },
                        "minItems": 2,
                        "maxItems": 2
                      }
                    ]
                  },
                "tags": {
                    "type": "array",
                    "items": {
                        "enum": [
                            "Rest",
                            "Easy Run",
                            "Run",
                            "Long Run",
                            "Cross Train",
                            "Race",
                            "Speedwork",
                            "Hills"
                        ]
                    },
                    "minItems": 1,
                    "uniqueItems": true
                }
            },
            "required": [
                "title"
            ]
        }
    }
}

=== nanreh/calendar-hack/public/plans/json/frr_bt_02.json
{
   "id": "frr_bb_02",
   "name": "Faster Road Racing: Base Building Schedule 2",
   "description": "\"Base Training 2: Building up to 45 Miles (72 km) per Week\" from \"Faster Road Racing: 5K to Half Marathon\" by Pete D. Pfitzinger and Philip Latter.\"",
   "units": "mi",
   "source": "https://www.amazon.com/Faster-Road-Racing-Half-Marathon/dp/1450470459",
   "type": "Base",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{6:10}",
               "distance": 6.0
            },
            {
               "title": "General aerobic\n{3:5}",
               "distance": 3.0
            },
            {
               "title": "General aerobic\n{4:6}",
               "distance": 4.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{5:9}",
               "distance": 5.0
            },
            {
               "title": "Endurance\n{9:14}",
               "distance": 9.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{6:10}",
               "distance": 6.0
            },
            {
               "title": "General aerobic\n{3:5}",
               "distance": 3.0
            },
            {
               "title": "General aerobic\n{5:8}",
               "distance": 5.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{6:10}",
               "distance": 6.0
            },
            {
               "title": "Endurance\n{10:16}",
               "distance": 10.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{6:10}",
               "distance": 6.0
            },
            {
               "title": "General aerobic\n{3:5}",
               "distance": 3.0
            },
            {
               "title": "General aerobic\n{5:8}",
               "distance": 5.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{6:10}",
               "distance": 6.0
            },
            {
               "title": "Endurance\n{10:16}",
               "distance": 10.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{7:11}",
               "distance": 7.0
            },
            {
               "title": "General aerobic\n{3:5}",
               "distance": 3.0
            },
            {
               "title": "General aerobic + speed {6} w/ 8 x 100 m strides\n{6:10}",
               "distance": 6.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{7:11}",
               "distance": 7.0
            },
            {
               "title": "Endurance\n{10:16}",
               "distance": 10.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{7:11}",
               "distance": 7.0
            },
            {
               "title": "General aerobic\n{3:5}",
               "distance": 3.0
            },
            {
               "title": "Lactate threshold\n{7:11}\n18 min tempo run",
               "distance": 7.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{8:13}",
               "distance": 8.0
            },
            {
               "title": "Endurance\n{11:18}",
               "distance": 11.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{7:11}",
               "distance": 7.0
            },
            {
               "title": "General aerobic\n{3:5}",
               "distance": 3.0
            },
            {
               "title": "General aerobic + speed {7} w/ 8 x 100 m strides\n{7:11}",
               "distance": 7.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{8:13}",
               "distance": 8.0
            },
            {
               "title": "Endurance\n{11:18}",
               "distance": 11.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{8:13}",
               "distance": 8.0
            },
            {
               "title": "General aerobic\n{4:6}",
               "distance": 4.0
            },
            {
               "title": "Lactate threshold\n{8:13}\n20 min tempo run",
               "distance": 7.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{8:13}",
               "distance": 8.0
            },
            {
               "title": "Endurance\n{11:18}",
               "distance": 11.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{9:14}",
               "distance": 9.0
            },
            {
               "title": "General aerobic\n{4:6}",
               "distance": 4.0
            },
            {
               "title": "General aerobic + speed {8} w/ 8 x 100 m strides\n{8:13}",
               "distance": 7.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{9:14}",
               "distance": 9.0
            },
            {
               "title": "Endurance\n{12:19}",
               "distance": 12.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{9:14}",
               "distance": 9.0
            },
            {
               "title": "General aerobic\n{4:6}",
               "distance": 4.0
            },
            {
               "title": "Lactate threshold\n{8:13}\n22 min tempo run",
               "distance": 8.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{9:14}",
               "distance": 9.0
            },
            {
               "title": "Endurance\n{12:19}",
               "distance": 12.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{10:16}",
               "distance": 10.0
            },
            {
               "title": "General aerobic\n{5:8}",
               "distance": 4.0
            },
            {
               "title": "General aerobic + speed {8} w/ 8 x 100 m strides\n{8:13}",
               "distance": 8.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{10:16}",
               "distance": 10.0
            },
            {
               "title": "Endurance\n{12:19}",
               "distance": 12.0
            }
         ]
      }
   ]
}

=== nanreh/calendar-hack/public/plans/json/pfitz_more_than_85_recovery_4th.json
{
   "id": "pfitz_more_than_85_recovery_4th",
   "name": "Pfitzinger/Douglas: Marathon More Than 85 Miles per Week Recovery",
   "description": "\"More Than 85 Miles per Week Recovery: Training Block 5 - Recovery\" from \"Advanced Marathoning\" (fourth edition) by Pete Pfitzinger and Scott Douglas",
   "units": "mi",
   "source": "https://www.amazon.com/dp/1718237472/",
   "type": "Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {8:13}",
               "distance": 8
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {7:11}",
               "distance": 7
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5
            },
            {
               "title": "Gen-aerobic {10:16}",
               "distance": 10
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Recovery {7:11}",
               "distance": 7
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {8:13} with 8 x 100 m strides",
               "distance": 8
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic {8:13}",
               "distance": 8
            },
            {
               "title": "Gen-aerobic {10:16}",
               "distance": 10
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {9:14} with 8 x 100 m strides",
               "distance": 9
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Med-long {12:19}",
               "distance": 12
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Gen-aerobic {8:13}",
               "distance": 8
            },
            {
               "title": "Gen-aerobic + speed {10:16} with 10 x 100 m strides",
               "distance": 10
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "LT {10:16} with {4:6} at LT pace",
               "distance": 10
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Med-long {14:23}",
               "distance": 14
            }
         ]
      }
   ]
}

=== nanreh/calendar-hack/public/plans/json/pfitz_70_recovery_4th.json
{
   "id": "pfitz_70_recovery_4th",
   "name": "Pfitzinger/Douglas: Marathon 55 to 70 Miles per Week Recovery",
   "description": "\"55 to 70 Miles per Week Recovery: Training Block 5 - Recovery\" from \"Advanced Marathoning\" (fourth edition) by Pete Pfitzinger and Scott Douglas",
   "units": "mi",
   "source": "https://www.amazon.com/dp/1718237472/",
   "type": "Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Recovery {3-4:5-6}",
               "distance": [
                  3.0,
                  4.0
               ]
            },
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5.0,
                  6.0
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Recovery {4-6:6-10}",
               "distance": [
                  4.0,
                  6.0
               ]
            },
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5.0,
                  6.0
               ]
            },
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Gen-aerobic {7-8:11-13}",
               "distance": [
                  7.0,
                  8.0
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5.0,
                  6.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Gen-aerobic + speed {7-8:11-13} with 8 \u00d7 100 m strides",
               "distance": [
                  7.0,
                  8.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Gen-aerobic {8-9:13-14}",
               "distance": [
                  8.0,
                  9.0
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5.0,
                  6.0
               ]
            },
            {
               "title": "Gen-aerobic {9-10:14-16}",
               "distance": [
                  9.0,
                  10.0
               ]
            },
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Gen-aerobic + speed {8-9:13-14} with 8 \u00d7 100 m strides",
               "distance": [
                  8.0,
                  9.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Med-long run {10-11:16-18}",
               "distance": [
                  10.0,
                  11.0
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Recovery {6-7:10-11}",
               "distance": [
                  6.0,
                  7.0
               ]
            },
            {
               "title": "Gen-aerobic + speed {8-9:13-14} with 8 \u00d7 100 m strides",
               "distance": [
                  8.0,
                  9.0
               ]
            },
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Gen-aerobic + speed {8-9:13-14} with 8 \u00d7 100 m strides",
               "distance": [
                  8.0,
                  9.0
               ]
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5.0,
                  6.0
               ]
            },
            {
               "title": "Med-long run {11-13:18-21}",
               "distance": [
                  11.0,
                  13.0
               ]
            }
         ]
      }
   ]
}

=== nanreh/calendar-hack/public/plans/json/c25k.json
{
   "id": "c25k",
   "name": "Couch to 5K",
   "description": "One of the more popular \"Couch to 5K\" plans to get you off the couch and running 5K without stopping in 8 weeks.",
   "units": "km",
   "source": "https://www.coachweb.com/couch-to-5k",
   "type": "5K",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "Run 30 seconds, walk 30 seconds. Repeat 15 times",
               "description": "Run 30 seconds, walk 30 seconds.\nRepeat 15 times"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Run/walk 10 minutes",
               "description": "Run/walk 10 minutes"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Walk 5km"
            },
            {
               "title": "Rest"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "Run 45 seconds, walk 45 seconds. Repeat 12 times",
               "description": "Run 45 seconds, walk 45 seconds.\nRepeat 12 times"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Run/walk 15 minutes"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Walk 5km (aim to beat previous week's time)",
               "description": "Walk 5km\n(aim to beat previous week's time)"
            },
            {
               "title": "Rest"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "Run 60 seconds, walk 60 seconds. Repeat 10 times",
               "description": "Run 60 seconds, walk 60 seconds.\nRepeat 10 times"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Run/walk 20 minutes"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Walk 5km (aim to beat previous week's time)",
               "description": "Walk 5km\n(aim to beat previous week's time)"
            },
            {
               "title": "Rest"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "Run 90 seconds, walk 90 seconds. Repeat 8 times",
               "description": "Run 90 seconds, walk 90 seconds.\nRepeat 8 times"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Run/walk 25 minutes"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Run 1km, walk 4km"
            },
            {
               "title": "Rest"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "Run 2 minutes, walk 2 minutes. Repeat 6 times",
               "description": "Run 2 minutes, walk 2 minutes.\nRepeat 6 times"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Run/walk 30 minutes"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Run 2km, walk 3km"
            },
            {
               "title": "Rest"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "Run 3 minutes, walk 2 minutes. Repeat 5 times",
               "description": "Run 3 minutes, walk 2 minutes.\nRepeat 5 times"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Run/walk 35 minutes"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Run 3km, walk 2km"
            },
            {
               "title": "Rest"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "Run 5 minutes, walk 2 minutes. Repeat 4 times",
               "description": "Run 5 minutes, walk 2 minutes.\nRepeat 4 times"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Run/walk 40 minutes"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Run 4km, walk 1km"
            },
            {
               "title": "Rest"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "Run 10 minutes, walk 60 seconds. Repeat 3 times",
               "description": "Run 10 minutes, walk 60 seconds.\nRepeat 3 times"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Run/walk 45 minutes"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Race Day!"
            }
         ]
      }
   ]
}
