=== nanreh/calendar-hack/public/schema/plan-schema.json
{
    "description": "Plan schema",
    "$id": "https://defy.org/plan",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "pattern": "^[a-z0-9]+(?:_[a-z0-9]+)*$"
        },
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "type": {
            "enum": [
                "Base",
                "Multiple Distances",
                "Marathon",
                "Half Marathon",
                "5K",
                "10K",
                "15K/10M",
                "50K",
                "100K",
                "100M"
            ]
        },
        "units": {
            "enum": [
                "mi",
                "km"
            ]
        },
        "source": {
            "type": "string"
        },
        "schedule": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/week"
            },
            "minItems": 1
        }
    },
    "required": [
        "id",
        "name",
        "description",
        "units",
        "source",
        "type",
        "schedule"
    ],
    "definitions": {
        "week": {
            "type": "object",
            "properties": {
                "description": {"type": "string"},
                "distance": {"type": "number"},
                "workouts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/workout"
                    },
                    "minItems": 7,
                    "maxItems": 7
                }
            },
            "required": [
                "workouts"
            ]
        },
        "workout": {
            "type": "object",
            "properties": {
                "title": {"type": "string"},
                "description": {"type": "string"},
                "distance": {
                    "anyOf": [
                      { "type": "number" },
                      {
                        "type": "array",
                        "items": { "type": "number" },
                        "minItems": 2,
                        "maxItems": 2
                      }
                    ]
                  },
                "tags": {
                    "type": "array",
                    "items": {
                        "enum": [
                            "Rest",
                            "Easy Run",
                            "Run",
                            "Long Run",
                            "Cross Train",
                            "Race",
                            "Speedwork",
                            "Hills"
                        ]
                    },
                    "minItems": 1,
                    "uniqueItems": true
                }
            },
            "required": [
                "title"
            ]
        }
    }
}

=== nanreh/calendar-hack/public/plans/json/pfitz_12_55.json
{
   "id": "pfitz_12_55",
   "name": "Pfitzinger/Douglas: Up to 55 miles per week, 12-week schedule",
   "description": "\"Up to 55 miles per week, 12-week schedule\" from \"Advanced Marathoning\" (third edition) by Pete Pfitzinger and Scott Douglas",
   "units": "mi",
   "source": "https://www.amazon.com/gp/product/149256866X/",
   "type": "Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {8:13} with 6 x 10 sec hill sprints + 8 x 100 m strides",
               "distance": 8.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic {9:14}",
               "distance": 9.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "Marathon-pace run {13:21} with {8:13} at marathon pace",
               "distance": 13.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "LT {8:13} with {4:6} at LT pace",
               "distance": 8.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "Med-long run {15:24}",
               "distance": 15.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {8:13} with 6 x 10 sec hill sprints + 8 X 100 m strides",
               "distance": 8.0
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4.0
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4.0
            },
            {
               "title": "Marathon-pace run {16:26} with {10:16} at marathon pace",
               "distance": 16.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "LT {10:16} with {5:8} at LT pace",
               "distance": 10.0
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "Long run {17:27}",
               "distance": 17.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Med-long run {12:19}",
               "distance": 12.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "LT {9:14} with {4:6} at LT pace",
               "distance": 9.0
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "Long run {16:26}",
               "distance": 16.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "VO\u2082max {10:16} with 5 x 1,000 m at 5K race pace; jog 50-90% interval time",
               "distance": 10.0
            },
            {
               "title": "Med-long run {12:19}",
               "distance": 12.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {6:10} with 6 x 100 m strides",
               "distance": 6.0
            },
            {
               "title": "Marathon-pace run {15:24} with {12:19} at marathon pace",
               "distance": 15.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {6:10} with 6 x 100 m strides",
               "distance": 6.0
            },
            {
               "title": "Med-long run {12:19}",
               "distance": 12.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "LT {12:19} with {7:11} at LT pace",
               "distance": 12.0
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "Long run {20:32}",
               "distance": 20.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "VO\u2082max {8:13} with 5 x 600 m at 5K race pace; jog 50-90% interval time",
               "distance": 8.0
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {4:6} with 6 x 100 m strides",
               "distance": 4.0
            },
            {
               "title": "8K-15K tune-up race (total 9-13 miles [14-21 km])",
               "distance": 9.0
            },
            {
               "title": "Long run {17:27}",
               "distance": 17.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {7:11} with 6 x 100 m strides",
               "distance": 7.0
            },
            {
               "title": "VO\u2082max {10:16} with 4 x 1,200 m at 5K race pace; jog 50-90% interval time",
               "distance": 10.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11.0
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4.0
            },
            {
               "title": "Long run {20:32}",
               "distance": 20.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "VO\u2082max {8:13} with 5 x 600 m at 5K race pace; jog 50-90% interval time",
               "distance": 8.0
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {4:6} with 6 x 100 m strides",
               "distance": 4.0
            },
            {
               "title": "8K-10K tune-up race (total 9-11 miles [14-18 km])",
               "distance": 9.0
            },
            {
               "title": "Long run {16:26}",
               "distance": 16.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {7:11} with 8 x 100 m strides",
               "distance": 7.0
            },
            {
               "title": "VO\u2082max {8:13} with 4 x 1,200 m at 5K race pace; jog 50-90% interval time",
               "distance": 8.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {5:8} with 6 x 100 m strides",
               "distance": 5.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Med-long run {12:19}",
               "distance": 12.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6.0
            },
            {
               "title": "Dress rehearsal {7:11} with {2:3} at marathon pace",
               "distance": 7.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "Recovery + speed {5:8} with 6 x 100 m strides",
               "distance": 5.0
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4.0
            },
            {
               "title": "Plan Ends",
               "distance": 26.2
            }
         ]
      }
   ]
}

=== nanreh/calendar-hack/public/plans/json/higdon_nov_half1.json
{
   "id": "higdon_nov_half1",
   "name": "Hal Higdon: Half Marathon Novice 1",
   "description": "Hal Higdon: Half Marathon Novice 1: \"The Novice 1 program is designed for beginning runners who want to prepare for their first 13.1-mile race. If 13.1 is more than enough race mileage with no desires to go 26.2 (at least for now), you have discovered one of our most gentle training programs. If you can handle the 3-to-4-mile runs prescribed in Week 1, this program will get you ready to run 13.1 week at the end of 12 weeks.\" (more details at the link below)",
   "units": "mi",
   "source": "https://www.halhigdon.com/training-programs/half-marathon-training/novice-1-half-marathon/",
   "type": "Half Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{2:3.2} run",
               "distance": 2.0
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "30 min cross"
            },
            {
               "title": "{4:6.4} run",
               "distance": 4.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{2:3.2} run",
               "distance": 2.0
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "30 min cross"
            },
            {
               "title": "{4:6.4} run",
               "distance": 4.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3.5:5.6} run",
               "distance": 3.5
            },
            {
               "title": "{2:3.2} run",
               "distance": 2.0
            },
            {
               "title": "{3.5:5.6} run",
               "distance": 3.5
            },
            {
               "title": "Rest"
            },
            {
               "title": "40 min cross"
            },
            {
               "title": "{5:8.0} run",
               "distance": 5.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3.5:5.6} run",
               "distance": 3.5
            },
            {
               "title": "{2:3.2} run",
               "distance": 2.0
            },
            {
               "title": "{3.5:5.6} run",
               "distance": 3.5
            },
            {
               "title": "Rest"
            },
            {
               "title": "40 min cross"
            },
            {
               "title": "{5:8.0} run",
               "distance": 5.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{4:6.4} run",
               "distance": 4.0
            },
            {
               "title": "{2:3.2} run",
               "distance": 2.0
            },
            {
               "title": "{4:6.4} run",
               "distance": 4.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "40 min cross"
            },
            {
               "title": "{6:9.6} run",
               "distance": 6.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{4:6.4} run",
               "distance": 4.0
            },
            {
               "title": "{2:3.2} run",
               "distance": 2.0
            },
            {
               "title": "{4:6.4} run",
               "distance": 4.0
            },
            {
               "title": "Rest or Easy Run"
            },
            {
               "title": "Rest"
            },
            {
               "title": "5-K Race",
               "distance": 3.1
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{4.5:7.2} run",
               "distance": 4.5
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{4.5:7.2} run",
               "distance": 4.5
            },
            {
               "title": "Rest"
            },
            {
               "title": "50 min cross"
            },
            {
               "title": "{7:11.2} run",
               "distance": 7.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{4.5:7.2} run",
               "distance": 4.5
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{4.5:7.2} run",
               "distance": 4.5
            },
            {
               "title": "Rest"
            },
            {
               "title": "50 min cross"
            },
            {
               "title": "{8:12.8} run",
               "distance": 8.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{5:8.0} run",
               "distance": 5.0
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{5:8.0} run",
               "distance": 5.0
            },
            {
               "title": "Rest or Easy Run"
            },
            {
               "title": "Rest"
            },
            {
               "title": "10-K Race",
               "distance": 6.2
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{5:8.0} run",
               "distance": 5.0
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{5:8.0} run",
               "distance": 5.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "60 min cross"
            },
            {
               "title": "{9:14.4} run",
               "distance": 9.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{5:8.0} run",
               "distance": 5.0
            },
            {
               "title": "{3:4.8} run",
               "distance": 3.0
            },
            {
               "title": "{5:8.0} run",
               "distance": 5.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "60 min cross"
            },
            {
               "title": "{10:16} run",
               "distance": 10.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{4:6.4} run",
               "distance": 4.0
            },
            {
               "title": "{3:4.6} run",
               "distance": 3.0
            },
            {
               "title": "{2:3.2} run",
               "distance": 2.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Half Marathon\n({13.1:21.1})",
               "distance": 13.1
            }
         ]
      }
   ]
}

=== nanreh/calendar-hack/public/plans/json/pfitz_06_multi_4th.json
{
   "id": "pfitz_06_multi_4th",
   "name": "Pfitzinger/Douglas: Multiple Marathoning, 6-week schedule",
   "description": "\"Multiple Marathoning, 6-week schedule\" from \"Advanced Marathoning\" (fourth edition) by Pete Pfitzinger and Scott Douglas",
   "units": "mi",
   "source": "https://www.amazon.com/dp/1718237472/",
   "type": "Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5.0,
                  6.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Recovery {6-7:10-11}",
               "distance": [
                  6.0,
                  7.0
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5.0,
                  6.0
               ]
            },
            {
               "title": "Gen-aerobic {7-8:11-13}",
               "distance": [
                  7.0,
                  8.0
               ]
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {7-8:11-13} with 8 x 100 m strides",
               "distance": [
                  7.0,
                  8.0
               ]
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5.0,
                  6.0
               ]
            },
            {
               "title": "Gen-aerobic {9-10:14-16}",
               "distance": [
                  9.0,
                  10.0
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {7-8:11-13} with 8 x 100 m strides",
               "distance": [
                  7.0,
                  8.0
               ]
            },
            {
               "title": "Med-long run {11-12:18-19}",
               "distance": [
                  11.0,
                  12.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "V\u0307O\u2082max {8-9:13-14} with 6 x 600 m at 5K race pace; jog 50%-90% interval time",
               "distance": [
                  8.0,
                  9.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Med-long run {13-14:21-23}",
               "distance": [
                  13.0,
                  14.0
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "V\u0307O\u2082max {8-9:13-14} with 6 x 600 m at 5K race pace; jog 50%-90% interval time",
               "distance": [
                  8.0,
                  9.0
               ]
            },
            {
               "title": "Gen-aerobic {9-10:14-16}",
               "distance": [
                  9.0,
                  10.0
               ]
            },
            {
               "title": "Recovery + speed {5-6:8-10} with 6 x 100 m strides",
               "distance": [
                  5.0,
                  6.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "8K-10K tune-up race (total {10-12:16-19})",
               "distance": [
                  10.0,
                  12.0
               ]
            },
            {
               "title": "Long run {16-17:26-27}",
               "distance": [
                  16.0,
                  17.0
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {6-7:10-11} with 8 x 100 m strides",
               "distance": [
                  6.0,
                  7.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "V\u0307O\u2082max {8-9:13-14} with 6 x 600 m at 5K race pace; jog 50%-90% interval time",
               "distance": [
                  8.0,
                  9.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Recovery + speed {6-7:10-11} with 8 x 100 m strides",
               "distance": [
                  6.0,
                  7.0
               ]
            },
            {
               "title": "Med-long run {12-13:19-21}",
               "distance": [
                  12.0,
                  13.0
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5.0,
                  6.0
               ]
            },
            {
               "title": "Dress rehearsal {6-7:10-11} with {2:3} at marathon pace",
               "distance": [
                  6.0,
                  7.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Recovery + speed {4-5:6-8} with 6 x 100 m strides",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Recovery {2-4:3-6}",
               "distance": [
                  2.0,
                  4.0
               ]
            },
            {
               "title": "Second marathon",
               "distance": 26.2
            }
         ]
      }
   ]
}
